### ISSUE TITLE
_ contains entire lib

### ISSUE THREAD

**Issue by algesten** [elclanrs/essential.js#3]
This row:

https://github.com/elclanrs/essential.js/blob/master/src/essential.coffee#L245

Do you really mean to alter '_' to contain the entire library? Or do you actually want immutable objects? ;)

**Comment by elclanrs** [comment]
Not sure what you mean. That line exports `extend` by using partial application, and `_` is a placeholder.

So this:
```coffeescript
module.exports.expose = partial extend, _, module.exports
```
would be like:
```coffeescript
module.exports.expose = (obj) ->
  extend obj, module.exports
```

So then you can add all the functions to the global object for example:
```coffeescript
require('essentialjs').expose(window)
```
