### ISSUE TITLE
isType and typeof inconsistent

### ISSUE THREAD

**Issue by algesten** [elclanrs/essential.js#4]
`isType` expects the argument to be uppercased `Object`, `String`
while `typeof` returns lowercased `object`, `string`

I think it would be reasonable to want the following to be true

```
> o = {}
> isType typeof(o), o
false    # I expected true!
```

furthermore `isType` can handle `Array`, but `typeof` doesn't (it says `object`).

```
> a = []
> typeof a
'object'
> isType 'Array', a
true
```

**Comment by elclanrs** [comment]
This is meant to be like that. `typeof` isn't reliable, the point is to avoid using it at all.
